
version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
  db:
    image: postgres:13
    environment:
      POSTGRES_DB=g_invoicing
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  supabase:
    image: supabase/postgres
    ports:
      - "5433:5432"
