
version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./infra/docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/web/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend

  backend:
    build: ./apps/api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
