
replicaCount: 2
image:
  repository: g-invoicing/app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: g-invoicing.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources: {}
