name: Close Stale Issues and PRs

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale. Comment to keep it open.'
          stale-pr-message: 'This PR is stale. Please update or it will be closed.'
          days-before-stale: 30
          days-before-close: 7