name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd apps/api && npm install
        cd ../../apps/web && npm install

    - name: Run API Tests
      run: |
        cd apps/api && npx jest

    - name: Run Frontend Tests
      run: |
        cd ../../apps/web && npx vitest run
